version: '3.8'

services:
  # 🍃 DATABASE (QUAN TRỌNG: Thêm để fix lỗi In-memory)
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    deploy:
      placement:
        constraints: [node.role == manager]

  # 1. CỔNG GÁC TRAEFIK
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=nbao1502@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certs:/letsencrypt"
    networks:
      - app-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  # 🔵 PHÂN KHU BLUE
  app-blue:
    image: nbao1502/final:${BLUE_IMAGE_TAG}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/products_db
    networks:
      - app-network
    deploy:
      replicas: ${BLUE_REPLICAS:-3}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app-blue.rule=Host(`namcloud.xyz`)"
        - "traefik.http.routers.app-blue.entrypoints=websecure"
        - "traefik.http.routers.app-blue.tls.certresolver=myresolver"
        - "traefik.http.services.app-blue.loadbalancer.server.port=3000"

  # 🟢 PHÂN KHU GREEN
  app-green:
    image: nbao1502/final:${GREEN_IMAGE_TAG}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/products_db
    networks:
      - app-network
    deploy:
      replicas: ${GREEN_REPLICAS:-0}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app-green.rule=Host(`namcloud.xyz`)"
        - "traefik.http.routers.app-green.entrypoints=websecure"
        - "traefik.http.routers.app-green.tls.certresolver=myresolver"
        - "traefik.http.services.app-green.loadbalancer.server.port=3000"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  app-network:
    driver: overlay # Overlay network để Manager và Worker nhìn thấy nhau

volumes:
  traefik-certs:
  mongo-data: # Lưu trữ dữ liệu MongoDB bền vững