global:
  scrape_interval: 15s

scrape_configs:
  # Tự giám sát bản thân Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Thu thập CPU/RAM/Disk của các máy ảo (Node Exporter)
  - job_name: 'node-exporter'
    dns_sd_configs:
      - names: ['tasks.node-exporter']
        type: 'A'
        port: 9100

  # Thu thập tài nguyên của từng Container (cAdvisor)
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: 'A'
        port: 8080