cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.47.2
  privileged: true
  user: root
  command:
    - '--docker_only=true'
    - '--listen_ip=0.0.0.0'   # 🔥 QUAN TRỌNG
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  networks:
    - app-network
  deploy:
    mode: global